[package]
name = "vegafusion-core"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "^1.0.29"
bytes = "1.1.0"
prost = "0.8.0"
prost-types = "0.8.0"
arrow = {version="5.5.0", default_features=false}
datafusion = {version="5.0.0", optional=true}

[build-dependencies]
prost-build = "0.8.0"
