[package]
name = "vegafusion-core"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "^1.0.29"
bytes = "1.1.0"
prost = "0.8.0"
prost-types = "0.8.0"
arrow = {version="5.5.0", default_features=false}
datafusion = { path = "../../../repos/arrow-datafusion/datafusion", optional=true}
itertools = "0.10.1"
lazy_static = "^1.4.0"
regex = "^1.5.4"
serde = { version="1.0.130", features=["derive"] }
serde_json = "1.0.68"

[build-dependencies]
prost-build = "0.8.0"
