[package]
name = "vegafusion-python"
version = "0.0.2"
edition = "2021"
license = "AGPL-3.0-or-later"

[lib]
name = "vegafusion"
crate-type = ["cdylib"]

[dependencies]
vegafusion-core = {path = "../vegafusion-core", features=["datafusion", "pyo3"]}
vegafusion-rt-datafusion = {path = "../vegafusion-rt-datafusion"}
tokio = { version = "1.10.1", features = ["macros", "rt-multi-thread"] }

[dependencies.pyo3]
version = "0.15.1"
features = ["extension-module"]
